### ISSUE TITLE
TypeError: str.join()

### ISSUE THREAD

**Issue by tabreturn** [jyksnw/install-jdk#65]
I run --

```
jdk.install('17')  # with and without a path argument
```

It looks like JDK downloads, but is perhaps failing at the extract step. I'm using Linux (x86_64, Ubuntu 22.04-based distro). Here's the output --

```
Traceback (most recent call last):
  File "_____/env/lib/python3.10/site-packages/jdk/__init__.py", line 102, in install
    jdk_dir = _decompress_archive(jdk_file, jdk_ext, path)
  File "_____/env/lib/python3.10/site-packages/jdk/__init__.py", line 70, in _decompress_archive
    jdk_directory = extractor.extract_files(
  File "_____/env/lib/python3.10/site-packages/jdk/extractor.py", line 71, in extract_files
    _safe_extract(tar, path=destination_folder)
  File "_____/env/lib/python3.10/site-packages/jdk/extractor.py", line 45, in _safe_extract
    member_path = path.join(path, member.name)
TypeError: str.join() takes exactly one argument (2 given)
```

Let me know if you need more info.

**Comment by jyksnw** [comment]
Hi @tabreturn, thanks for reporting this. I have got it corrected with a new version pushed out to pypi.
